insert into "pickup_lines" (content) values
('I’m not a photographer, but I can picture me and you together.'),
('Do I know you? ‘Cause you look a lot like my next girlfriend.'),
('Do you know what my shirt is made of? Boyfriend material!'),
('For some reason, I was feeling a little off today. But when you came along, you definitely turned me on.'),
('Are you sure you’re not tired? You’ve been running through my mind all day'),
('Do you believe in love at first sight or should I pass by again?'),
('Kiss me if I’m wrong, but dinosaurs still exist, right?'),
('Did it hurt? When you fell from heaven?'),
('Is your name Google? Because you have everything I’ve been searching for.'),
('If nothing lasts forever, will you be my nothing?'),
('Can you take me to the doctor? Because I just broke my leg falling for you.'),
('Your body is made up of 70% water. . .and I’m thirsty.'),
('Can I borrow a kiss? I promise I’ll give it back.'),
('What is a nice person like you doing in a dirty mind like mine?'),
('I’m not feeling myself today. Can I feel you instead?'),
('Let’s play Titanic. You’ll be the iceberg and I’ll go down.'),
('I’m an adventurer and I want to explore you.'),
('I’d never play hide and seek with you because someone like you is impossible to find'),
('You may fall from the sky, you may fall from a tree, but the best way to fall… is in love with me.'),
('Can I follow you? Cause my mom told me to follow my dreams'),
('Are you a camera? Because every time I look at you, I smile.'),
('Roses are red violets are blue I didn’t know what perfect was until I met you'),
('You’re That “Nothing” When People Ask Me What I’m Thinking About.'),
('If I had 4 quarters to give to the 4 prettiest girls in the world, you would have a dollar.'),
('You know what’s beautiful? Read the first word.'),
('Roses are red, violets are blue, it would be a shame if I couldn’t date you!'),
('Can you touch me? I want to tell my friends I was touched by an Angel.'),
('Roses are red and violets are blue there’s nothing in the world more prettier than you')
;
